markdown_body() {
  awk 'NR == 1 && $0 == "---" { front = 1; next } front && $0 == "---" { front = 0; next } !front { print }' "$1"
}

preserve_generated_destination() {
  local dest="$1" legacy="${2:-}"
  if [[ -L "$dest" ]]; then
    if [[ -n "$legacy" && "$(readlink "$dest")" == "$legacy" ]]; then
      run rm "$dest"
    else
      backup_file "$dest"
    fi
  elif [[ -e "$dest" ]] && ! grep -q -e '^<!-- Generated by dotfiles/install.sh -->$' -e '^# Generated by dotfiles/install.sh$' "$dest"; then
    backup_file "$dest"
  fi
}

install_generated_file() {
  local dest="$1" renderer="$2" preserve="$3" preserve_arg="$4" tmp
  shift 4
  tmp="$(mktemp "${dest}.tmp.XXXXXX")" || return 1
  if ! "$renderer" "$@" > "$tmp"; then
    rm "$tmp"
    error "Failed to generate $dest"
    return 1
  fi
  "$preserve" "$dest" "$preserve_arg" "$@" || { rm "$tmp"; return 1; }
  mv "$tmp" "$dest" || { rm "$tmp"; return 1; }
}

render_instructions() {
  local persona="$1" optional="$2" local_override="$3" harness="${4:-}"
  printf '<!-- Generated by dotfiles/install.sh -->\n\n'
  cat "$DOTFILES_DIR/.agents/AGENTS.md" || return
  if [[ "$persona" == true ]]; then
    printf '\n'
    cat "$DOTFILES_DIR/.agents/personas/my-humble-servant.md" || return
  fi
  if [[ "$optional" == true ]]; then
    printf '\n## Unsupported workflows\n\n'
    printf 'This adapter does not install specialist roles. Do not run my-build,\nmy-security, or my-review without their required specialist roles. Run\nmy-plan only when the harness provides independent exploration subagents.\n'
  fi
  if [[ "$harness" == grok ]]; then
    cat <<'EOF'

## Grok review context

Supply the full diff and test results to `_my-reviewer` and
`_my-security-reviewer`. Include task requirements and the task baseline.
These agents cannot run git or tests. A commit range alone is not enough.
If context is missing, have the reviewer request the missing context.
EOF
  fi
  if [[ -f "$local_override" ]]; then
    printf '\n'
    cat "$local_override" || return
  fi
}
