markdown_body() {
  awk 'NR == 1 && $0 == "---" { front = 1; next } front && $0 == "---" { front = 0; next } !front { print }' "$1"
}

preserve_generated_destination() {
  local dest="$1" legacy="${2:-}"
  if [[ -L "$dest" ]]; then
    if [[ -n "$legacy" && "$(readlink "$dest")" == "$legacy" ]]; then
      run rm "$dest"
    else
      backup_file "$dest"
    fi
  elif [[ -e "$dest" ]] && ! grep -q -e '^<!-- Generated by dotfiles/install.sh -->$' -e '^# Generated by dotfiles/install.sh$' "$dest"; then
    backup_file "$dest"
  fi
}

install_generated_file() {
  local dest="$1" renderer="$2" preserve="$3" preserve_arg="$4" tmp
  shift 4
  tmp="$(mktemp "${dest}.tmp.XXXXXX")" || return 1
  if ! "$renderer" "$@" > "$tmp"; then
    rm "$tmp"
    error "Failed to generate $dest"
    return 1
  fi
  "$preserve" "$dest" "$preserve_arg" "$@" || { rm "$tmp"; return 1; }
  mv "$tmp" "$dest" || { rm "$tmp"; return 1; }
}

render_instructions() {
  local persona="$1" optional="$2" local_override="$3" harness="${4:-}"
  printf '<!-- Generated by dotfiles/install.sh -->\n\n'
  cat "$DOTFILES_DIR/.agents/AGENTS.md" || return
  if [[ "$persona" == true ]]; then
    printf '\n'
    cat "$DOTFILES_DIR/.agents/personas/my-humble-servant.md" || return
  fi
  if [[ "$optional" == true ]]; then
    printf '\n## Unsupported workflows\n\n'
    printf 'This adapter does not install specialist roles. Do not run my-build,\nmy-security, or my-review without their required specialist roles. Run\nmy-plan only when the harness provides independent exploration subagents.\n'
  fi
  if [[ "$harness" == grok ]]; then
    cat <<'EOF'

## Grok review context

Supply the full diff and test results to `_my-reviewer` and
`_my-security-reviewer`. Include task requirements and the task baseline.
These agents cannot run git or tests. A commit range alone is not enough.
If context is missing, have the reviewer request the missing context.
EOF
  fi
  if [[ -f "$local_override" ]]; then
    printf '\n'
    cat "$local_override" || return
  fi
}

preserve_instructions_destination() {
  local dest="$1" state="$2" source="$5" local_override="${1%.md}.local.md"
  case "$state" in
    legacy) rm "$dest" || return ;;
    custom) backup_file "$dest" || return ;;
  esac
  [[ ! -d "$local_override" ]] || backup_file "$local_override" || return
  if [[ "$source" != "$local_override" ]]; then
    [[ ! -L "$local_override" ]] || backup_file "$local_override" || return
    mv "$source" "$local_override" || return
  fi
}

install_instructions() {
  local dest="$1" persona="$2" optional="${3:-false}" harness="${4:-}" local_override="${1%.md}.local.md" old="" state=generated local_tmp="" source
  ensure_directory "$(dirname "$dest")"
  if $DRY_RUN; then
    info "Generating $dest from neutral rules"
    return
  fi
  if [[ -L "$dest" ]]; then
    case "$(readlink "$dest")" in
      "$DOTFILES_DIR/.claude/CLAUDE.md"|"$DOTFILES_DIR/.agents/AGENTS.md") state=legacy ;;
      *) state=custom ;;
    esac
  elif [[ -d "$dest" ]] || { [[ -f "$dest" ]] && ! grep -q '^<!-- Generated by dotfiles/install.sh -->$' "$dest"; }; then
    state=custom
  fi
  if [[ "$state" == custom && -f "$dest" ]] && ! grep -q '^<!-- Generated by dotfiles/install.sh -->$' "$dest"; then
    old="$(cat "$dest")" || return
  fi
  source="$local_override"
  if [[ -n "$old" ]]; then
    local_tmp="$(mktemp "${local_override}.tmp.XXXXXX")" || return
    if [[ -f "$local_override" ]]; then
      cat "$local_override" > "$local_tmp" || { rm "$local_tmp"; return 1; }
    fi
    printf '\n%s\n' "$old" >> "$local_tmp" || { rm "$local_tmp"; return 1; }
    source="$local_tmp"
  fi
  if ! install_generated_file "$dest" render_instructions preserve_instructions_destination "$state" "$persona" "$optional" "$source" "$harness"; then
    [[ -z "$local_tmp" ]] || rm "$local_tmp"
    return 1
  fi
}

install_native_agents() {
  local harness="$1" dir="$2" src name dest template
  case "$harness" in
    claude) ensure_directory "$dir" "$DOTFILES_DIR/.claude/agents" ;;
    opencode) ensure_directory "$dir" "$DOTFILES_DIR/.opencode/agents" ;;
    *) ensure_directory "$dir" ;;
  esac
  for src in "$DOTFILES_DIR"/.agents/agents/_my-*.md; do
    name="$(basename "$src" .md)"
    template=""
    case "$harness" in
      claude|opencode|grok) dest="$dir/$name.md"; template="$DOTFILES_DIR/.$harness/templates/agents/$name.md" ;;
      copilot) dest="$dir/$name.agent.md"; template="$DOTFILES_DIR/.copilot/agents/$name.agent.md" ;;
      codex) dest="$dir/$name.toml" ;;
    esac
    if $DRY_RUN; then
      info "Generating $dest from $src"
      continue
    fi
    install_generated_file "$dest" render_native_agent preserve_generated_destination "$template" "$harness" "$src" "$name" "$template" || return
  done
}

render_native_agent() {
  local harness="$1" src="$2" name="$3" template="$4" description
  if [[ "$harness" == codex ]]; then
    description="$(sed -n 's/^description: //p' "$src" | head -n 1)" || return
    printf '# Generated by dotfiles/install.sh\n'
    printf 'name = '
    printf '%s' "$name" | jq -Rs . || return
    printf 'description = '
    printf '%s' "$description" | jq -Rs . || return
    [[ "$name" == _my-implementer ]] || printf 'sandbox_mode = "read-only"\n'
    printf 'developer_instructions = '
    markdown_body "$src" | jq -Rs . || return
  else
    cat "$template" || return
    printf '\n<!-- Generated by dotfiles/install.sh -->\n\n'
    markdown_body "$src" || return
  fi
}

render_shared_export() {
  local skill
  render_instructions true false "" || return
  printf '\n## Skills\n\nLoad each skill file explicitly if the harness has no native skill discovery.\n\n'
  for skill in "$DOTFILES_DIR"/.agents/skills/my-*; do
    printf -- '- `%s`: `%s/SKILL.md`' "$(basename "$skill")" "$HOME/.agents/skills/$(basename "$skill")"
    case "$(basename "$skill")" in
      my-build) printf ' — requires implementation and review subagents with specialist roles.' ;;
      my-security) printf ' — requires an independent read-only security-reviewer role.' ;;
      my-review) printf ' — requires an independent read-only reviewer role.' ;;
      my-plan) printf ' — requires independent exploration subagents.' ;;
    esac
    printf '\n'
  done
}

link_skills() {
  local dir="$1" skill
  for skill in "$DOTFILES_DIR"/.agents/skills/my-*; do
    link_file "$skill" "$dir/$(basename "$skill")"
  done
}

install_shared_agents() {
  local src dest="$HOME/.agents/exports/default.md"
  ensure_directory "$HOME/.agents"
  link_file "$DOTFILES_DIR/.agents/AGENTS.md" "$HOME/.agents/AGENTS.md"
  ensure_directory "$HOME/.agents/personas"
  link_file "$DOTFILES_DIR/.agents/personas/my-humble-servant.md" "$HOME/.agents/personas/my-humble-servant.md"
  ensure_directory "$HOME/.agents/agents"
  for src in "$DOTFILES_DIR"/.agents/agents/_my-*.md; do
    link_file "$src" "$HOME/.agents/agents/$(basename "$src")"
  done
  ensure_directory "$HOME/.agents/skills"
  link_skills "$HOME/.agents/skills"
  ensure_directory "$HOME/.agents/exports"
  if $DRY_RUN; then
    info "Generating manual export $dest"
    return
  fi
  install_generated_file "$dest" render_shared_export preserve_generated_destination ""
}

render_claude_style() {
  local template="$1"
  cat "$template" || return
  printf '\n<!-- Generated by dotfiles/install.sh -->\n\n'
  cat "$DOTFILES_DIR/.agents/personas/my-humble-servant.md" || return
}

install_claude() {
  local dest="$CLAUDE_DIR/output-styles/my-humble-servant.md" template="$DOTFILES_DIR/.claude/templates/output-styles/my-humble-servant.md"
  ensure_directory "$CLAUDE_DIR"
  merge_json_file "$DOTFILES_DIR/.claude/settings.json" "$CLAUDE_DIR/settings.json" "$CLAUDE_DIR/settings.local.json" claude
  install_instructions "$CLAUDE_DIR/CLAUDE.md" false
  link_file "$DOTFILES_DIR/.claude/statusline.sh" "$CLAUDE_DIR/statusline.sh"
  ensure_directory "$CLAUDE_DIR/skills" "$DOTFILES_DIR/.claude/skills"
  link_skills "$CLAUDE_DIR/skills"
  install_native_agents claude "$CLAUDE_DIR/agents"
  ensure_directory "$CLAUDE_DIR/output-styles" "$DOTFILES_DIR/.claude/output-styles"
  if $DRY_RUN; then
    info "Generating $dest"
    return
  fi
  install_generated_file "$dest" render_claude_style preserve_generated_destination "$template" "$template"
}

install_opencode() {
  ensure_directory "$OPENCODE_DIR"
  install_instructions "$OPENCODE_DIR/AGENTS.md" false
  merge_json_file "$DOTFILES_DIR/.opencode/opencode.json" "$OPENCODE_DIR/opencode.json" "$OPENCODE_DIR/opencode.local.json" opencode
  install_native_agents opencode "$OPENCODE_DIR/agents"
}

install_codex() {
  ensure_directory "$CODEX_DIR"
  install_codex_config "$CODEX_DIR/config.toml"
  install_instructions "$CODEX_DIR/AGENTS.md" true
  install_native_agents codex "$CODEX_DIR/agents"
}

install_copilot() {
  ensure_directory "$COPILOT_DIR"
  install_instructions "$COPILOT_DIR/copilot-instructions.md" true
  install_native_agents copilot "$COPILOT_DIR/agents"
}

grok_notification_commands_are_notify_only() {
  jq -e '
    def commands: [.. | objects | .command? // empty | select(type == "string")];
    (commands | length) > 0 and (commands | all(. == "../notify.sh"))
  ' "$1" >/dev/null 2>&1
}

# Drop the notification hook this installer used to copy.
# Leave custom hook files alone, and never follow a symlinked hooks directory.
remove_managed_grok_notifications() {
  local notify="$GROK_DIR/notify.sh" hooks="$GROK_DIR/hooks" dest
  dest="$hooks/notifications.json"
  if [[ -L "$notify" ]]; then
    info "Removing $notify"
    run rm -- "$notify"
  fi
  if [[ -L "$hooks" || ! -f "$dest" || -L "$dest" ]]; then
    return 0
  fi
  if grok_notification_commands_are_notify_only "$dest"; then
    info "Removing $dest"
    run rm -- "$dest"
  fi
}

install_grok() {
  ensure_directory "$GROK_DIR"
  install_instructions "$GROK_DIR/AGENTS.md" true false grok
  install_native_agents grok "$GROK_DIR/agents"
  install_grok_config "$GROK_DIR/config.toml"
  link_file "$DOTFILES_DIR/.grok/statusline.sh" "$GROK_DIR/statusline.sh"
  remove_managed_grok_notifications
}

install_optional() {
  local tool="$1" dir="$2" file="$3"
  ensure_directory "$dir"
  install_instructions "$dir/$file" true true
  if [[ "$tool" == gemini && "$GEMINI_DIR" != "$HOME/.gemini" ]]; then
    ensure_directory "$dir/skills"
    link_skills "$dir/skills"
  fi
}

install_agents() {
  local tool
  command -v jq &>/dev/null || { error "jq is required for agent installation"; return 1; }
  install_shared_agents
  for tool in "${SELECTED_TOOLS[@]}"; do
    case "$tool" in
      claude) install_claude ;;
      codex) install_codex ;;
      opencode) install_opencode ;;
      copilot) install_copilot ;;
      grok) install_grok ;;
      gemini) install_optional gemini "$GEMINI_DIR" GEMINI.md ;;
      amp) install_optional amp "$AMP_DIR" AGENTS.md ;;
    esac
  done
}
